"""Initial Case table

Revision ID: 7e668cf6df52
Revises: 
Create Date: 2026-09-20 16:01:10.384852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e668cf6df52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('caseId', sa.String(), nullable=False),
    sa.Column('patientId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('consentGranted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('caseId')
    )
    op.create_index(op.f('ix_cases_caseId'), 'cases', ['caseId'], unique=False)
    op.create_index(op.f('ix_cases_patientId'), 'cases', ['patientId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_patientId'), table_name='cases')
    op.drop_index(op.f('ix_cases_caseId'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
