"""Add patient documents

Revision ID: 964722f960ee
Revises: 8c2f1b7d9a4e
Create Date: 2026-09-25 08:58:19.447928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964722f960ee'
down_revision: Union[str, None] = '8c2f1b7d9a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('caseId', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storagePath', sa.String(), nullable=False),
    sa.Column('mimeType', sa.String(), nullable=False),
    sa.Column('sizeBytes', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caseId'], ['cases.caseId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_caseId'), 'documents', ['caseId'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_caseId'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
